version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    ports:
      - "5432:5432"  # expõe para conexões externas
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu_pgadmin
    restart: always
    ports:
      - "5050:80"  # acesso via http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres